export const ActionTypes = {
  'GET_WINNERS': 'GET_WINNERS',
  'GET_WINNERS_SUCCESS': 'GET_WINNERS_SUCCESS',
  'GET_WINNERS_FAILURE': 'GET_WINNERS_FAILURE',
  'GET_GAME_SETTINGS': 'GET_GAME_SETTINGS',
  'GET_GAME_SETTINGS_FAILURE': 'GET_GAME_SETTINGS_FAILURE',
  'GET_GAME_SETTINGS_SUCCESS':'GET_GAME_SETTINGS_SUCCESS'
};
